# =============================================================================
# External Secrets Operator Configuration
# =============================================================================
# Integrates with AWS Secrets Manager for secure secret management.
#
# Prerequisites:
# 1. Install External Secrets Operator:
#    helm install external-secrets external-secrets/external-secrets \
#      -n external-secrets --create-namespace
#
# 2. Create IRSA role for the operator with SecretsManager permissions
# =============================================================================

# ClusterSecretStore for AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

---
# ExternalSecret for application secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fastapi-app-secrets
  namespace: production
spec:
  refreshInterval: 1h

  # Reference to the ClusterSecretStore
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  # Target Kubernetes secret
  target:
    name: fastapi-app-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Template for secret data
        DATABASE_URL: "{{ .database_url }}"
        API_KEY: "{{ .api_key }}"
        JWT_SECRET: "{{ .jwt_secret }}"

  # Data to fetch from AWS Secrets Manager
  data:
    - secretKey: database_url
      remoteRef:
        key: hello-world/production/database
        property: url

    - secretKey: api_key
      remoteRef:
        key: hello-world/production/api
        property: key

    - secretKey: jwt_secret
      remoteRef:
        key: hello-world/production/jwt
        property: secret

---
# ExternalSecret for staging (different secret path)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fastapi-app-secrets
  namespace: staging
spec:
  refreshInterval: 30m

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: fastapi-app-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_URL: "{{ .database_url }}"
        API_KEY: "{{ .api_key }}"
        JWT_SECRET: "{{ .jwt_secret }}"

  data:
    - secretKey: database_url
      remoteRef:
        key: hello-world/staging/database
        property: url

    - secretKey: api_key
      remoteRef:
        key: hello-world/staging/api
        property: key

    - secretKey: jwt_secret
      remoteRef:
        key: hello-world/staging/jwt
        property: secret

---
# IRSA ServiceAccount for External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/hello-world-external-secrets-irsa
