# =============================================================================
# Bootstrap Terraform - S3 Backend and DynamoDB Lock Table
# =============================================================================
# This module creates the S3 bucket and DynamoDB table required for storing
# Terraform state remotely. Run this LOCALLY before using GitHub Actions.
#
# Usage (run locally):
#   cd infrastructure/bootstrap
#   terraform init
#   terraform apply
#
# After apply:
#   - backend.hcl will be generated automatically
#   - Commit and push backend.hcl to GitHub
#   - Then run Infrastructure workflow via GitHub Actions
# =============================================================================

terraform {
  required_version = ">= 1.6"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

# -----------------------------------------------------------------------------
# Provider Configuration
# -----------------------------------------------------------------------------
provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project   = var.project_name
      ManagedBy = "Terraform-Bootstrap"
      Purpose   = "Terraform State Management"
    }
  }
}

# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------
variable "aws_region" {
  description = "AWS region for the S3 bucket and DynamoDB table"
  type        = string
  default     = "ap-south-1"
}

variable "project_name" {
  description = "Project name for resource naming"
  type        = string
  default     = "hello-world"
}

# -----------------------------------------------------------------------------
# Random suffix for globally unique bucket name
# -----------------------------------------------------------------------------
resource "random_id" "bucket_suffix" {
  byte_length = 4
}

# -----------------------------------------------------------------------------
# Locals
# -----------------------------------------------------------------------------
locals {
  bucket_name = "${var.project_name}-terraform-state-${random_id.bucket_suffix.hex}"
  table_name  = "${var.project_name}-terraform-lock"
}

# -----------------------------------------------------------------------------
# S3 Bucket for Terraform State
# -----------------------------------------------------------------------------
resource "aws_s3_bucket" "terraform_state" {
  bucket = local.bucket_name

  lifecycle {
    prevent_destroy = false
  }

  tags = {
    Name = local.bucket_name
  }
}

# Enable versioning for state history
resource "aws_s3_bucket_versioning" "terraform_state" {
  bucket = aws_s3_bucket.terraform_state.id

  versioning_configuration {
    status = "Enabled"
  }
}

# Enable server-side encryption
resource "aws_s3_bucket_server_side_encryption_configuration" "terraform_state" {
  bucket = aws_s3_bucket.terraform_state.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
    bucket_key_enabled = true
  }
}

# Block all public access
resource "aws_s3_bucket_public_access_block" "terraform_state" {
  bucket = aws_s3_bucket.terraform_state.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Lifecycle rule to clean up old state versions
resource "aws_s3_bucket_lifecycle_configuration" "terraform_state" {
  bucket = aws_s3_bucket.terraform_state.id

  rule {
    id     = "cleanup-old-versions"
    status = "Enabled"

    noncurrent_version_expiration {
      noncurrent_days = 90
    }

    noncurrent_version_transition {
      noncurrent_days = 30
      storage_class   = "STANDARD_IA"
    }
  }
}

# -----------------------------------------------------------------------------
# DynamoDB Table for State Locking
# -----------------------------------------------------------------------------
resource "aws_dynamodb_table" "terraform_lock" {
  name         = local.table_name
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"

  attribute {
    name = "LockID"
    type = "S"
  }

  point_in_time_recovery {
    enabled = true
  }

  tags = {
    Name = local.table_name
  }
}

# -----------------------------------------------------------------------------
# Generate backend.hcl file
# -----------------------------------------------------------------------------
resource "local_file" "backend_config" {
  filename = "${path.module}/../backend.hcl"
  content  = <<-EOT
    # =============================================================================
    # Terraform Backend Configuration (Auto-generated)
    # =============================================================================
    # Generated by: terraform apply (bootstrap module)
    # Timestamp: ${timestamp()}
    #
    # IMPORTANT: Commit this file to Git after bootstrap!
    # =============================================================================

    bucket         = "${aws_s3_bucket.terraform_state.id}"
    key            = "eks-cluster/terraform.tfstate"
    region         = "${var.aws_region}"
    encrypt        = true
    dynamodb_table = "${aws_dynamodb_table.terraform_lock.name}"
  EOT
}

# -----------------------------------------------------------------------------
# Outputs
# -----------------------------------------------------------------------------
output "s3_bucket_name" {
  description = "Name of the S3 bucket for Terraform state"
  value       = aws_s3_bucket.terraform_state.id
}

output "dynamodb_table_name" {
  description = "Name of the DynamoDB table for state locking"
  value       = aws_dynamodb_table.terraform_lock.name
}

output "backend_hcl_path" {
  description = "Path to the generated backend.hcl file"
  value       = local_file.backend_config.filename
}

output "next_steps" {
  description = "Instructions for next steps"
  value       = <<-EOT

    ✅ Bootstrap complete!

    Next steps:
    1. Commit and push backend.hcl:
       git add infrastructure/backend.hcl
       git commit -m "chore: Add backend.hcl from bootstrap"
       git push origin main

    2. Run Infrastructure workflow in GitHub Actions:
       Go to Actions → Infrastructure → Run workflow → apply

  EOT
}
