# ==============================================================================
# Argo CD Application - FastAPI Production
# ==============================================================================
#
# Production application with manual sync and additional safeguards.
#
# ==============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: fastapi

  source:
    repoURL: https://github.com/selvakumarperumal/k8s_hello_world.git
    # Use specific tag/branch for production
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-prod

  # Production uses MANUAL sync for safety
  syncPolicy:
    # Automated is disabled for production - require manual approval
    # automated:
    #   prune: true
    #   selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      # Validate resources before applying
      - Validate=true

    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  # Revision history limit
  revisionHistoryLimit: 10
